#!/bin/bash

HOMERUNPACE_DSN="postgres://$PGUSER:$POSTGRES_1_ENV_POSTGRES_PASSWORD@$POSTGRES_PORT_5432_TCP_ADDR:$POSTGRES_PORT_5432_TCP_PORT/$PGDB?sslmode=disable" \
HOMERUNPACE_ROOT="$APPROOT" \
HOMERUNPACE_TOKEN="$APPTOKEN" \
HOMERUNPACE_REDIS_NETWORK="$REDIS_PORT_6379_TCP_PROTO" \
HOMERUNPACE_REDIS_ADDRESS="$REDIS_PORT_6379_TCP_ADDR:$REDIS_PORT_6379_TCP_PORT" \
HOMERUNPACE_REDIS_MAX_IDLE="10" \
HOMERUNPACE_LOGFILE="$APPLOG" \
app
